### ISSUE TITLE
Support Wayland.

### ISSUE THREAD

**Issue by BEEDELLROKEJULIANLOCKHART** [Opticos/GWSL-Source#102]

**Comment by RokeJulianLockhart** [comment]
> https://github.com/Opticos/GWSL-Source/issues/102#event-5439313892

@Pololot64, is support transparent, or does something need to be configured to make use of it?

**Comment by Pololot64** [comment]
@RokeJulianLockhart . GWSL cannot support wayland. Also, I am not sure what you mean by transparent.

**Comment by RokeJulianLockhart** [comment]
> GWSL cannot support Wayland.

@Pololot64, why not? Regardless, if so, this issue should be closed as invalid/unplanned, rather than "completed".

> Also, I am not sure what you mean by transparent.

Nor I, in retrospect! last time I configured GWSL was some years ago, so I forget what kind of configuration it requires. However, I was probably requesting confirmation that it wouldn't induce something like a Wayland compositor as a window nested under X. [^1]

[^1]: [`unix.stackexchange.com/q/482129`](https://unix.stackexchange.com/q/482129/386242)
