### ISSUE TITLE
GWSL 1.4.0 - ERROR - Exception occurred - SSH mode failure

### ISSUE THREAD

**Issue by igrokit** [Opticos/GWSL-Source#124]
When connecting with graphical SSH via the GUI, connection is possible. All works well.

At the same time, a link is created in %APPDATA%\GWSL, with the name "Graphical SSH on 192.168.1.88 port 22"
Target:   `C:\Users\username\AppData\Local\Microsoft\WindowsApps\gwsl.exe --r --ssh --ip="192.168.1.88:22" --command="open_putty"`

When executing that link, nothing happens and the following is written into the dashboard.log:

> 2022-01-22 23:43:19,073 - GWSL 1.4.0 - ERROR - Exception occurred - SSH mode failure
> Traceback (most recent call last):
>   File "manager.py", line 4627, in <module>
>   File "manager.py", line 3007, in get_login
> NameError: name 'ui' is not defined

Is that link supposed to work? 
If yes, why does it not?

Dan

**Comment by Pololot64** [comment]
Hey Dan,

I fixed this in the code but have yet to create a release (because the current version is very stable and I don't want to mess it up).

However, I did make a small test version with the bug fixed that I sent to someone else with the issue:

https://drive.google.com/file/d/1e4RDn9Exa4HFuxV3tL9NVJQTnRxu-Ffe/view?usp=sharing

You can uninstall the store/github version if you want. (It is not necessary though just don't confuse both versions). Then extract this file anywhere and make a shortcut to GWSL.exe in the start menu. This will function exactly as before, and shortcuts should work.

I put it in drive since it isn't tested as much as the current version but eventually the changes will make it out to the official.

Sincerely,
Paul

**Comment by igrokit** [comment]
Thanks @Pololot64 ,
Good that it is a known issue and there is a fix.
By the way, does that eventually also fix the issue with Start Menu links not being created?
In my case, I can go through the process of settig up a Start Menu link with "Shortcut Creator" or use the link symbol in the App menu, but the button "Add to Start Menu" won't do anything. Well, except it will create the named link in %APPDATA%\GWSL, but it will not place it into the Start Menu. Could the problem be related?

I will try the link you sent eventually, but I also might just wait for the next release. 
Thanks for your fast response.

Way cool that tool GWSL... Thanks!


Dan

**Comment by Pololot64** [comment]
😎 glad you like it.

The issue with the start menu is not related. It is strange that it is not showing up. Is it possible that it appears after a reboot? 

As for the update. I will do my best to get it released but I am in college now so it's pretty busy here. 🙂
