### ISSUE TITLE
gwsl cann't open jetbrains toolbox

### ISSUE THREAD

**Issue by mensylisir** [Opticos/GWSL-Source#146]
chmod a+w /usr/share/applications
touch /usr/share/applications/toolbox.desktop
vim /usr/share/applications/toolbox.desktop
[Desktop Entry]
Encoding=UTF-8
Name=toolbox
GenericName=toolbox
Comment=toolbox for gwsl
Exec="~/jetrabins-toolbox/jetrabins-toolbox" %f
Terminal=false
Type=Application
Categories=Application;Programme;

**Comment by Pololot64** [comment]
Can you upload dashboard.log from the log button in the gwsl systray menu?

**Comment by kam1sh** [comment]
Hello! I can confirm that behavior: I got black window instead of JetBrains Toolbox app.
![Снимок экрана (22)](https://user-images.githubusercontent.com/14600211/173483257-fbc0e061-c98f-44be-b1e1-122d5abfd3a9.png)
I looked at the Toolbox logs, it hangs up on something, I don't even. understand why. Logs in the attachment
[toolbox.log](https://github.com/Opticos/GWSL-Source/files/8895928/toolbox.log)
.

But what's interesting is that if you change XServer profile to `Fullscreen`, then it works in standalone mode. And it even better works with window managers like XFCE!
![image](https://user-images.githubusercontent.com/14600211/173484046-922bce0a-43e8-42a7-9505-230587a8c8ea.png)


service.log:
```
2022-06-14 06:04:20,585 - __main__ - ERROR - Exception occurred in main loop
Traceback (most recent call last):
  File "main.py", line 615, in main
SystemExit
2022-06-14 06:04:21,159 - __main__ - ERROR - Exception occurred - Cannot Start Service. Make sure the settings file is not corrupted.
Traceback (most recent call last):
  File "main.py", line 615, in main
SystemExit

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 697, in <module>
  File "main.py", line 621, in main
SystemExit
```

dashboard.log is empty :/

**Comment by Pololot64** [comment]
Hmm. The problem is that this really depends on distro configuration and many other variables. It works on most pc's. It may be best in your case to directly link to the jet brains apps you are using.
