### ISSUE TITLE
Spikes in CPU load

### ISSUE THREAD

**Issue by fheck** [Opticos/GWSL-Source#25]
While running the app in background I noticed that there are usage spikes about every 5 seconds. I was not yet able to pinpoint which component is directly responsible, but it directly correlates with GWSL running. 

I can probably exclude VcXsrv as the culprit since I had been running the most recent standalone version and haven't notices this behavior before.

The 5 second interval of usage of about one full core is a bit annoying, since that keeps the CPU from reducing the core frequency and therefore my fan is constantly spinning.

Further system info: latest Windows 10 2009 Release Preview build, 2 Ubuntu WSL instances, one WSL1 (always running), one WSL2 (running on demand).

**Comment by Pololot64** [comment]
That is probably caused by the GWSL systray service which performs checks every few seconds to make sure vcxsrv is still running. It calls tasklist.exe to check this. In 1.3.6 it also checked the current taskbar color theme to adjust for contrast. I took this call out as the new icon I made looks good on both. When I release 1.3.7 (after just a little more testing) it will still spike but probably less dramatically. In theory the checks can be made less often but this could lead to alot of confusion.

**Comment by fheck** [comment]
Thanks for the response.
I tried to get track down the source further on my own. I could see the calls to `tasklist.exe`, but initially I ignored them, because the process itself does not use significant resources. It turns out, tasklist uses WMI to query for the list of running processes and the WMI service seems to be a key contributor to the spike.
I haven't looked too deep into the source code of your app yet, but if you just need to check if the VcXsrv instance is running, it might be reasonable just to get its PID once and check if the process is running, alternatively you could use `psutils.process_iter()`, which, from what I've read is a lot faster.

**Comment by Pololot64** [comment]
I considered using psutils but am hesitant as it may not work well with packaging for the sandboxed Microsoft Store version. I can do some more testing but it is possible that the lack of a registry read in the new version will help some already. If you want you can download the 1.3.7 beta archive and extract it to a random location. Then run GWSL_service.exe and see if it spikes. If it spikes less, it is because of the lack of the registry read.

**Comment by fheck** [comment]
Thanks for the info, unfortunately, the spikes are still there. I still believe they stem from invoking WMI, as WMI service and host rise to the top in task manager/process explorer when the gwsl service is running.

As I haven't done much UWP development yet, I can't say how psutils handles that, but maybe I could try looking into that.

**Comment by Pololot64** [comment]
Ok. You can do that if you wanto but I can do some quick fiddling to see if I can do it for 1.3.8.
