### ISSUE TITLE
Maximize client-side decoration window overlapped with taskbar

### ISSUE THREAD

**Issue by codehz** [Opticos/GWSL-Source#35]
Like gedit, vscode with custom titlebar.
(it has been fixed in [x410](https://x410.dev/), but it is closed-source product)

**Comment by Pololot64** [comment]
I do not exactly understand what you mean but if it is in the vcxsrv code I cannot fix it.

**Comment by codehz** [comment]
![image](https://user-images.githubusercontent.com/13158903/107303217-9f5b8000-6ab9-11eb-8a6c-156368cab6f2.png)

if I click the maximize button for gedit, and notice the taskbar is disappeared... and I cannot restore the window by click maximize button again, I have to resize window manually

**Comment by codehz** [comment]
if it is hard to fix, can you add an option to use alternative x11 implemention? since x410 has no problem with it

**Comment by Pololot64** [comment]
There may be a way to use x410 . Block gwsl's access to the firewall and run x410. That might do the trick but I wouldn't know as I do not have x410. They might conflict with each other. I cannot fix the problem itself because I am not the maintainer of vcxsrv. The developers did make an update but I don't know if it fixes the problem. I am pretty sure x410 is just a retouched fork of vcxsrv but like you said they hide the source code.
