### ISSUE TITLE
Use lint tool

### ISSUE THREAD

**Issue by vasilvestre** [Opticos/GWSL-Source#4]
I would love to participate (at least on my first issue about display variable.) but I found extra spaces in files for no reason.

In order to get help, adding a linter to project and CI would be a nice addition imho

**Comment by Pololot64** [comment]
That sounds good. I unfortunately do not have experience with linters or "CI"'s. Any recommendations?

**Comment by vasilvestre** [comment]
Not for Py, but Github action is free (and should be ok for your needs)

**Comment by sanzoghenzo** [comment]
HI, here's a list of good tools that comes in handy

- [black](https://black.readthedocs.io/en/stable/) for formatting;
- [mypy](http://mypy-lang.org/) for type checking;
- [flake8](https://flake8.pycqa.org/en/latest/) (and plugins) for linting;
- [autoflake](https://pypi.org/project/autoflake/) to fix some lint errors automatically;
- [isort](https://pycqa.github.io/isort/) (I prefer [reorder-python-imports](https://pypi.org/project/reorder-python-imports/)) to... reorder python imports 😉;
- [pre-commit](https://pre-commit.com/) to run the aforementioned tools when creating a commit.

Basically, you just need to add some configuration files for those tools, do `pip install pre-config` and `pre-commit install`;
this way the pre-commit hooks are installed and run everytime you do a commit.
You can also run it manually on every file of the project via `pre-commit run --all-files`;
There's also the [official github action](https://github.com/pre-commit/action) that will run the checks on the commits and PRs (useful if contributors forget to install the hooks).

Obviously I would also add [pytest](https://docs.pytest.org/en/stable/) for unit testing and pytest-cov to make sure your code is properly tested.
The [github documentation](https://docs.github.com/en/free-pro-team@latest/actions/guides/building-and-testing-python#testing-with-pytest-and-pytest-cov) explains how to create a github action for pytest.
For better insights on the code coverage, you can use [codecov](https://github.com/codecov/codecov-action).

I can setup something for, but some settings are subjective.
The first thing to choose is the desired line length; I've settled with 80 for my projects, so that I can have two panes in my IDE for faster copy/pasting or testing, etc.

**Comment by Pololot64** [comment]
I have the github action for pylint turned on at the moment. What annoys me is that the big things it dislikes are not changeable and are necessary for the code to work. I am not sure how to git around this.

**Comment by sanzoghenzo** [comment]
To configure pylint behaviour you have to put a `pylintrc` in the root directory.
To disable specific checks on lines or entire modules see the [FAQ](http://pylint.pycqa.org/en/latest/faq.html#message-control).
Also, since pylint is a static checker, you don't need to install the dependencies of your project.
