### ISSUE TITLE
Stutter with glxgears.

### ISSUE THREAD

**Issue by LucioAmely** [Opticos/GWSL-Source#55]
Greetings, I'm using GWSL to connect to my prooted linux distro which is running within Termux on my android device. Everything works fine except two things:

1. 3D applications seems like not working except VcXsrv is in multi window configuration. (Error: couldn't get an RGB, Double-buffered visual.)
2. I get 1000+ fps in glxgears while in multi window configuration but the spin animation constantly stutters. Seems like stutters are not random and happening in regular intervals. This made me think like it may be a refresh rate / (v)sync problem with my Windows desktop.

I would be so glad if you help me out.

**Comment by Pololot64** [comment]
I am not exactly sure what is causing the first problem but I can say that glxgears _never_ works with GWSL or most vcxsrv windows based xservers. One person once got it working but they had to recompile with glxgears code edits.. I cannot fix it on my end. At least I think I cant. It might be fixable with vcxsrv flags.

It is usually best to test with the apps you actually need to run since lots of benchmarks are bizzare.
