### ISSUE TITLE
PyCharm crash after PC hibernation

### ISSUE THREAD

**Issue by cornel-masson** [Opticos/GWSL-Source#89]
I'm using Windows 10 with WSL2. I use PyCharm for Linux with the GWSL X server, and it's working fine. However, after PC hibernation (not sleep, hibernate) PyCharm always crashes. When I try to restart it after that, PyCharm doesn't start: does nothing. I have to reboot the WSL Ubuntu (18.04), after which I can start PyCharm again. It's mildly irritating, since this action obviously closes my open terminal sessions as well. The PyCharm team have not been able to reproduce or offer a solution. Attached are syslogs around the time of crash.

[syslogs.tar.gz](https://github.com/Opticos/GWSL-Source/files/7019778/syslogs.tar.gz)

**Comment by Pololot64** [comment]
It is a WSL issue that is reported alot: https://github.com/microsoft/WSL/issues/4992
https://github.com/microsoft/WSL/issues/5876
https://github.com/microsoft/WSL/issues/5821#issuecomment-684092757

However, this seems to be a fix: https://github.com/nbdd0121/wsld

**Comment by noctuid** [comment]
@Pololot64 How are you supposed to use the two together? Wsld expects DISPLAY to be exported as ":0" while gwsl expects something different. Wsld expects the X server to run on TCP port 6000. It has an option to specify a different port (e.g. `wsldhost.exe --daemon --display localhost:<port>`), but so far I have not found any configuration where wsld actually works and my apps don't crash after sleep.

**Comment by noctuid** [comment]
I don't have a full understanding of exactly how wsld works, but it is supposed to be over vsock not over TCP (because TCP is exactly what causes the crashing issue). [You cannot export DISPLAY as as "ip:0" or it will use TCP](https://github.com/nbdd0121/wsld/issues/7#issuecomment-783807756).

You are supposed to set DISPLAY as ":0".  "Wsld" runs in wsl2 and forwards everything to the wlsdhost program running outside wsl over vsock. The host program only then forwards to tcp port 6000 (or whatever configured port that the X server should listen to).

Are wsld and gwsl incompatible? Also, what port is gwsl using by default?

**Comment by Pololot64** [comment]
GWSL should be listening on port 6000+the display number you are currently using. So most likely 6000. I don't think it is incompatible. If it works with vcxsrv it should with GWSL but I have not tested it and (am honestly not the best at networking either).
